routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Funcionario;
// use Illuminate\Routing\Route;

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::redirect('/', '/home');
    // Route::any('/home', 'HomeController@index')->name('home');
    Route::any('/home', 'HomeController@index')->name('homesuperior');

    // Funcionários
    Route::resource('/funcionario', 'FuncionarioController');

    Route::get('/funcionario/novo', function () {
        return view('funcionario.formulario');
    });
    // Cargos
    Route::resource('/cargo', 'CargoController');

    // Vínculos
    Route::resource('/vinculo', 'VinculoController');

    // Escolaridade
    Route::resource('/escolaridade', 'EscolaridadeController');
    Route::get('/escolaridade/remove/{id}', 'EscolaridadeController@delete');
    Route::get('/escolaridade/ativar/{id}', 'EscolaridadeController@ativar');

    // Grau de Parentesco
    Route::resource('/grauparentesco', 'GrauParentescoController');
    Route::get('/grauparentesco/remove/{id}', 'GrauParentescoController@delete');

    // Banco
    Route::resource('/banco', 'BancoController');
    Route::get('/banco/remove/{id}', 'BancoController@delete');

    // Tipo de Pagamento
    Route::resource('/tipopagamento', 'TipoPagamentoController');
    Route::get('/tipopagamento/remove/{id}', 'TipoPagamentoController@delete');

    // Horario de Trabalho
    Route::resource('/horariotrabalho', 'HorarioTrabalhoController');

    // Lotação
    Route::resource('/lotacao', 'LotacaoController');
    Route::get('/lotacao/remove/{id}', 'LotacaoController@delete');
    Route::get('/lotacao/ativar/{id}', 'LotacaoController@ativar');

    // Férias
    //Route::resource('/ferias','FeriasController');
    //Route::get('/ferias/cadastro/{idFunc}', 'FeriasController@createFerias');
    //Route::post('/ferias/', 'FeriasController@store');
    //Route::get('/ferias/', 'FeriasController@index');
    // Route::get('/ferias/edit/{id}', 'FeriasController@edit');
    //Route::get('resultFuncionario', array('as'=>'resultFuncionario','uses'=>'FeriasController@resultFuncionario'));

    // Férias Solicitação
    Route::resource('/ferias/solicitacao', 'FeriasSolicitacaoController');
    Route::post('/ferias/solicitacao/enviarAprovacao', 'FeriasSolicitacaoController@enviarAprovacaoSuperior');

    //Alterar Data
    Route::get('/ferias/solicitacao/{feriasSolicitacao}/edit', 'FeriasSolicitacaoController@edit')->name('edit');

    //visualizar histórico de férias
    Route::get('visualiza/historico/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoes')->name('historico');
    //visao superior ou rh
    Route::get('visualiza/avaliacao/{tipoAvaliador}/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoesAvaliador')->name('historicoavaliador');

    // Férias Avaliação Chefe imediato
    Route::resource('/ferias/avaliacao/superior', 'FeriasAvaliacaoSuperiorController');
    Route::get('/ferias/avaliacao/lista', 'FeriasAvaliacaoSuperiorController@index_avaliados');


    //Férias Avaliação RH
    Route::resource('/ferias/avaliacao/rh', 'FeriasAvaliacaoRHController');
    Route::get('resultAvalRHFerias', array('as' => 'resultAvalRHFerias', 'uses' => 'FeriasAvaliacaoRHController@resultAvalRHFerias'));

    // Lotação
    Route::resource('/turno', 'TurnoController');
    Route::get('/turno/remove/{id}', 'TurnoController@delete');
    Route::get('/turno/ativar/{id}', 'TurnoController@ativar');
});

resources/views/formulario.blade.php
@extends('layouts.pagina')

@section('content')

<div class="col-12">

@include('messages.alert')

@if($banco->exists)
    <div class="col-12 text-center">
        <h3>EDITAR BANCO</h3>
    </div>

    <form action="{{route('banco.update', $banco)}}" method="post">
        <input type="hidden" name="_method" value="put">

@else

    <div class="col-12 text-center">
        <h3>CADASTRO DE BANCO</h3>
    </div>

    <form action="{{route('banco.store')}}" method="post">
@endif
        {{ csrf_field() }}

            <div class="form-group col-3">
                <label>Código *</label>
                <input name="codigo" id="codigo" value="{{old('codigo',$banco->codigo)}}" type="text" class="form-control codebanco"  required />
            </div>

            <div class="form-group col-9">
                <label>Descrição *</label>
                <input name="descricao" id="descricao" value="{{old('descricao',$banco->descricao)}}" type="text" class="form-control" placeholder="Digite o nome do banco" required />
            </div>


        <div class="row">
            <div class="form-group form-footer col-12 text-center" style="margin-bottom: 50px">

                <button class="btn btn-primary" type="submit">Salvar</button>

                <a class="btn btn-default" href="{{route('banco.index')}}">
                    Cancelar
                </a>
            </div>
        </div>

        </form>

</div>
@endsection

resources/views/home.blade.php
@extends('layouts.pagina')

@section('content')
    <div class="col-12">
        @include('messages.alert')
        <div class="dashboard">
            Funcionários Cadastrados: {{$qtd}} <br>
        </div>
        <div class="row" style="background-color: #ececec; border-radius: 10px">
            {{-- Ficha Funcional --}}
            <div class="col-sm-3 col-lg-3 text-center mt-3 mb-5">
                <h3>Ficha <br> Funcional</h3>

                <a href="{{ route('funcionario.create') }}">
                    <div class="btn btn-block btn-primary">
                        Cadastro
                    </div>
                </a>

                <button type="button" class="btn btn-block mt-3 btn-primary" data-toggle="modal"
                    data-target="#exampleModalCenter">
                    Buscar Colaborador
                </button>

                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Buscar Funcionário</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="{{ route('funcionario.index') }}" method="get">
                                    <div class="input-group mb-3">
                                        <input type="search" placeholder="MATRICULA,CPF ou NOME"
                                            value="{{ isset($busca) ? $busca : '' }}" id="busca" name="busca"
                                            class="busca form-control">

                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary">Pesquisar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>





                <a href="#">
                    <div class="btn btn-block btn-primary mt-3 disabled">
                        Remoção
                    </div>
                </a>
                <a href="#">
                    <div class="btn btn-block btn-primary mt-3 disabled">
                        Anotação
                    </div>
                </a>

            </div>

            {{-- Lic. Médica e Atestado --}}
            <div class="col-sm-3 text-center mt-3">
                <h3>Lic. Médica e <br> Atestado</h3>

                <a href="#">
                    <div class="btn btn-block btn-primary disabled">
                        Cadastro
                    </div>
                </a>

                <a href="#">
                    <div class="btn btn-block btn-primary mt-3 disabled">
                        Encaminhamento à Junta Médica
                    </div>
                </a>

            </div>

            {{-- Lic. Interesse Particular --}}
            <div class="col-sm-3 text-center mt-3">
                <h3>Lic. Interesse<br> Particular</h3>

                <a href="#">
                    <div class="btn btn-block btn-primary disabled">
                        Cadastro
                    </div>
                </a>

                <a href="#">
                    <div class="btn btn-block btn-primary disabled mt-3">
                        Lançamentos
                    </div>
                </a>

            </div>

            {{-- Lic. Especial --}}
            <div class="col-sm-3 text-center mt-3">
                <h3>Lic.<br>Especial</h3>

                <a href="#">
                    <div class="btn btn-block btn-primary disabled">
                        Cadastro
                    </div>
                </a>

                <a href="#">
                    <div class="btn btn-block btn-primary disabled mt-3">
                        Lançamentos
                    </div>
                </a>

            </div>
        </div>
    </div>
@endsection

resources/views/homesuperior.blade.php
@extends('layouts.pagina')

@section('content')
    <div class="col-12">
        @include('messages.alert')
        <div class="row" style="background-color: #ececec; border-radius: 10px">
            {{-- Ficha Funcional --}}
            <div class="col-sm-3 col-lg-3 text-center mt-3 mb-5">
                <h3>Solicitação de Férias</h3>

                <a href="{{url('ferias/solicitacao')}}">
                    <div class="btn btn-block btn-primary">
                        Solicitar Férias
                    </div>
                </a>


            </div>
        </div>
    @endsection