routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Funcionario;
// use Illuminate\Routing\Route;

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::redirect('/', '/home');
    // Route::any('/home', 'HomeController@index')->name('home');
    Route::any('/home', 'HomeController@index')->name('homesuperior');

    // Funcionários
    Route::resource('/funcionario', 'FuncionarioController');

    Route::get('/funcionario/novo', function () {
        return view('funcionario.formulario');
    });
    // Cargos
    Route::resource('/cargo', 'CargoController');

    // Vínculos
    Route::resource('/vinculo', 'VinculoController');

    // Escolaridade
    Route::resource('/escolaridade', 'EscolaridadeController');
    Route::get('/escolaridade/remove/{id}', 'EscolaridadeController@delete');
    Route::get('/escolaridade/ativar/{id}', 'EscolaridadeController@ativar');

    // Grau de Parentesco
    Route::resource('/grauparentesco', 'GrauParentescoController');
    Route::get('/grauparentesco/remove/{id}', 'GrauParentescoController@delete');

    // Banco
    Route::resource('/banco', 'BancoController');
    Route::get('/banco/remove/{id}', 'BancoController@delete');

    // Tipo de Pagamento
    Route::resource('/tipopagamento', 'TipoPagamentoController');
    Route::get('/tipopagamento/remove/{id}', 'TipoPagamentoController@delete');

    // Horario de Trabalho
    Route::resource('/horariotrabalho', 'HorarioTrabalhoController');

    // Lotação
    Route::resource('/lotacao', 'LotacaoController');
    Route::get('/lotacao/remove/{id}', 'LotacaoController@delete');
    Route::get('/lotacao/ativar/{id}', 'LotacaoController@ativar');

    // Férias
    //Route::resource('/ferias','FeriasController');
    //Route::get('/ferias/cadastro/{idFunc}', 'FeriasController@createFerias');
    //Route::post('/ferias/', 'FeriasController@store');
    //Route::get('/ferias/', 'FeriasController@index');
    // Route::get('/ferias/edit/{id}', 'FeriasController@edit');
    //Route::get('resultFuncionario', array('as'=>'resultFuncionario','uses'=>'FeriasController@resultFuncionario'));

    // Férias Solicitação
    Route::resource('/ferias/solicitacao', 'FeriasSolicitacaoController');
    Route::post('/ferias/solicitacao/enviarAprovacao', 'FeriasSolicitacaoController@enviarAprovacaoSuperior');

    //Alterar Data
    Route::get('/ferias/solicitacao/{feriasSolicitacao}/edit', 'FeriasSolicitacaoController@edit')->name('edit');

    //visualizar histórico de férias
    Route::get('visualiza/historico/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoes')->name('historico');
    //visao superior ou rh
    Route::get('visualiza/avaliacao/{tipoAvaliador}/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoesAvaliador')->name('historicoavaliador');

    // Férias Avaliação Chefe imediato
    Route::resource('/ferias/avaliacao/superior', 'FeriasAvaliacaoSuperiorController');
    Route::get('/ferias/avaliacao/lista', 'FeriasAvaliacaoSuperiorController@index_avaliados');


    //Férias Avaliação RH
    Route::resource('/ferias/avaliacao/rh', 'FeriasAvaliacaoRHController');
    Route::get('resultAvalRHFerias', array('as' => 'resultAvalRHFerias', 'uses' => 'FeriasAvaliacaoRHController@resultAvalRHFerias'));

    // Lotação
    Route::resource('/turno', 'TurnoController');
    Route::get('/turno/remove/{id}', 'TurnoController@delete');
    Route::get('/turno/ativar/{id}', 'TurnoController@ativar');
});

app/Cargo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cargo extends Model
{
    protected $table='cargos';
    public $fillable =['codigo','cargo','quadro','cargo_genericos_id'];
}

app/Http/Controllers/CargoController.php
<?php

namespace App\Http\Controllers;

use App\Cargo;
use App\Http\Requests\StoreCargo;
use App\Http\Requests\UpdateCargo;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CargoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cargos = Cargo::all();
        return view('cargos.index',compact('cargos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cargos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCargo $request)
    {
        DB::beginTransaction();
        $validado = $request->validated();
        $cargo = Cargo::create([
            'codigo'=>$validado['codigo'],
            'descricao'=>$validado['descricao'],
            'usuario_id_fk'=>auth()->user()->id
        ]);
        if(!$cargo){
            DB::rollBack();
            return redirect()->route('cargo.index')->with('error',"Não foi possível criar o cargo");
        }
        DB::commit();
        return redirect()->route('cargo.index')->with('status',"Cargo criado com sucesso");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cargo  $cargo
     * @return \Illuminate\Http\Response
     */
    public function show(Cargo $cargo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cargo  $cargo
     * @return \Illuminate\Http\Response
     */
    public function edit(Cargo $cargo)
    {
        // dd($cargo);
        return view('cargos.edit',compact('cargo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cargo  $cargo
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCargo $request, Cargo $cargo)
    {
        DB::beginTransaction();
        try{
            $cargo->update($request->validated());
        }catch(Exception $e){
            DB::rollBack();
            return redirect()->route('cargo.index')->with('error',"Não foi possível alterar o cargo");
        }
        DB::commit();
        return redirect()->route('cargo.index')->with('status',"Cargo alterado com sucesso");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cargo  $cargo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cargo $cargo)
    {
        //
    }
}

resources/views/cargos/create.blade.php
@extends('layouts.pagina')
@section('content')
    <div class="col-12">
        <h1>
            Novo cargo
        </h1>
        @include('messages.alert')
    </div>
    <div class="col-12">
        <form action="{{route('cargo.store')}}" method="post" class="form-row">
            @csrf
            <div class="form-group col-4">
                <label class="font-weight-bold">Código</label>
                <input type="text" name="codigo" id="codigo" class="form-control" placeholder="">
            </div>
            <div class="form-group col-8">
                <label class="font-weight-bold">Descrição</label>
                <input type="text" name="descricao" id="descricao" class="form-control" placeholder="">
            </div>
            <div class="col-12 text-center">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>

@endsection

resources/views/cargos/edit.blade.php
@extends('layouts.pagina')
@section('content')
    <div class="col-12">
        <h1>
            Editar cargo
        </h1>
        @include('messages.alert')
    </div>
    <div class="col-12">
        <form action="{{route('cargo.update',$cargo)}}" method="post" class="form-row">
            @csrf
            @method('put')
            <div class="form-group col-4">
                <label class="font-weight-bold">Código</label>
                <input type="text" name="codigo" value="{{$cargo->codigo}}" id="codigo" class="form-control" placeholder="">
            </div>
            <div class="form-group col-8">
                <label class="font-weight-bold">Descrição</label>
                <input type="text" name="descricao" value="{{$cargo->descricao}}" id="descricao" class="form-control" placeholder="">
            </div>
            <div class="col-12 text-center">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>

@endsection

resources/views/cargos/index.blade.php
@extends('layouts.pagina')
@section('content')
<div class="col-12">
    <h1>Cargos</h1>
</div>
<div class="col-12 text-center">
    <a class="btn btn-primary my-3" href="{{route('cargo.create')}}" role="button">
        Novo cargo
    </a>
    @include('messages.alert')
    <table class="table table-bordered">
        <thead>
            <tr class="bg-dark text-white text-center">
                <th>Código</th>
                <th>Descrição</th>
                <th width="10%">Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach($cargos as $c)
            <tr>
                <td>{{$c->codigo}}</td>
                <td>{{$c->cargo}}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-dark dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown">
                            Selecionar
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{route('cargo.edit',$c)}}">Editar</a>
                            <!-- <a class="dropdown-item" href="#">Excluir</a> -->
                        </div>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection