routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Funcionario;
// use Illuminate\Routing\Route;

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::redirect('/', '/home');
    // Route::any('/home', 'HomeController@index')->name('home');
    Route::any('/home', 'HomeController@index')->name('homesuperior');

    // Funcionários
    Route::resource('/funcionario', 'FuncionarioController');

    Route::get('/funcionario/novo', function () {
        return view('funcionario.formulario');
    });
    // Cargos
    Route::resource('/cargo', 'CargoController');

    // Vínculos
    Route::resource('/vinculo', 'VinculoController');

    // Escolaridade
    Route::resource('/escolaridade', 'EscolaridadeController');
    Route::get('/escolaridade/remove/{id}', 'EscolaridadeController@delete');
    Route::get('/escolaridade/ativar/{id}', 'EscolaridadeController@ativar');

    // Grau de Parentesco
    Route::resource('/grauparentesco', 'GrauParentescoController');
    Route::get('/grauparentesco/remove/{id}', 'GrauParentescoController@delete');

    // Banco
    Route::resource('/banco', 'BancoController');
    Route::get('/banco/remove/{id}', 'BancoController@delete');

    // Tipo de Pagamento
    Route::resource('/tipopagamento', 'TipoPagamentoController');
    Route::get('/tipopagamento/remove/{id}', 'TipoPagamentoController@delete');

    // Horario de Trabalho
    Route::resource('/horariotrabalho', 'HorarioTrabalhoController');

    // Lotação
    Route::resource('/lotacao', 'LotacaoController');
    Route::get('/lotacao/remove/{id}', 'LotacaoController@delete');
    Route::get('/lotacao/ativar/{id}', 'LotacaoController@ativar');

    // Férias
    //Route::resource('/ferias','FeriasController');
    //Route::get('/ferias/cadastro/{idFunc}', 'FeriasController@createFerias');
    //Route::post('/ferias/', 'FeriasController@store');
    //Route::get('/ferias/', 'FeriasController@index');
    // Route::get('/ferias/edit/{id}', 'FeriasController@edit');
    //Route::get('resultFuncionario', array('as'=>'resultFuncionario','uses'=>'FeriasController@resultFuncionario'));

    // Férias Solicitação
    Route::resource('/ferias/solicitacao', 'FeriasSolicitacaoController');
    Route::post('/ferias/solicitacao/enviarAprovacao', 'FeriasSolicitacaoController@enviarAprovacaoSuperior');

    //Alterar Data
    Route::get('/ferias/solicitacao/{feriasSolicitacao}/edit', 'FeriasSolicitacaoController@edit')->name('edit');

    //visualizar histórico de férias
    Route::get('visualiza/historico/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoes')->name('historico');
    //visao superior ou rh
    Route::get('visualiza/avaliacao/{tipoAvaliador}/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoesAvaliador')->name('historicoavaliador');

    // Férias Avaliação Chefe imediato
    Route::resource('/ferias/avaliacao/superior', 'FeriasAvaliacaoSuperiorController');
    Route::get('/ferias/avaliacao/lista', 'FeriasAvaliacaoSuperiorController@index_avaliados');


    //Férias Avaliação RH
    Route::resource('/ferias/avaliacao/rh', 'FeriasAvaliacaoRHController');
    Route::get('resultAvalRHFerias', array('as' => 'resultAvalRHFerias', 'uses' => 'FeriasAvaliacaoRHController@resultAvalRHFerias'));

    // Lotação
    Route::resource('/turno', 'TurnoController');
    Route::get('/turno/remove/{id}', 'TurnoController@delete');
    Route::get('/turno/ativar/{id}', 'TurnoController@ativar');
});

app/Escolaridade.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Escolaridade extends Model
{
    protected $table = 'escolaridades';
    use SoftDeletes;

    public $fillable = ['descricao'];

}

app/Http/Controllers/EscolaridadeController.php
<?php

namespace App\Http\Controllers;

use App\Escolaridade;
use App\Http\Requests\StoreEscolaridade;
use Illuminate\Http\Request;
use Request as rq;

class EscolaridadeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $escolaridades = Escolaridade::orderBy('descricao')->withTrashed()->get();

        return view('escolaridade.index', compact('escolaridades'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $escolaridade = new Escolaridade();

        return view('escolaridade.formulario', compact('escolaridade'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEscolaridade $request)
    {

        try{

            $escolaridade = Escolaridade::create([
                'descricao' => $request->descricao,
                'usuario_id_fk' => auth()->user()->id
            ]);

            if($escolaridade){
                rq::session()->flash('status', 'Escolaridade cadastrada com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar escolaridade.');
            }

        }catch(\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar escolaridade. '.$e->getMessage());
        }

        return redirect()->route('escolaridade.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Escolaridade  $escolaridade
     * @return \Illuminate\Http\Response
     */
    public function show(Escolaridade $escolaridade)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Escolaridade  $escolaridade
     * @return \Illuminate\Http\Response
     */
    public function edit(Escolaridade $escolaridade)
    {
        return view('escolaridade.formulario', compact('escolaridade'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Escolaridade  $escolaridade
     * @return \Illuminate\Http\Response
     */
    public function update(StoreEscolaridade $request, Escolaridade $escolaridade)
    {

        try{

            $escolaridade = $escolaridade->update([
                'descricao' => $request->descricao,
            ]);

            if($escolaridade){
                rq::session()->flash('status', 'Escolaridade atualizada com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar escolaridade.');
            }

        }catch(\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar escolaridade. '.$e->getMessage());
        }

        return redirect()->route('escolaridade.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Escolaridade  $escolaridade
     * @return \Illuminate\Http\Response
     */
    public function destroy(Escolaridade $escolaridade)
    {
        //
    }

    //para ativar apos soft delete
    public function ativar($id)
    {
        // Recupera pelo ID
        $escolaridade = Escolaridade::where('id', $id)->withTrashed()->first();

        // Restaura:
        $rest = $escolaridade->restore();

        if($rest){
            rq::session()->flash('status', 'Escolaridade ativada.');
        }else{
            rq::session()->flash('status-not', 'Ocorreu um erro ao ativar escolaridade.');
        }

        return redirect()->route('escolaridade.index');

    }

    //inativa com o soft delete
    public function delete($id)
    {
        $escolaridade = Escolaridade::findOrFail($id);

        try{
            $escolaridade->delete();
            rq::session()->flash('status', 'Escolaridade '.$escolaridade->descricao.' inativada com sucesso.');
            return redirect()->route('escolaridade.index');
        }
        catch (\Exception $e){

         /*
            if($e->getCode() == 23000 ){
                rq::session()->flash('status-not', 'Escolaridade não foi excluída. A mesma está sendo utilizada em outro cadastro! ');
            }else{
                rq::session()->flash('status-not', 'Escolaridade não foi excluída! '.$e->getMessage());
            }
          */

            rq::session()->flash('status-not', 'Escolaridade não foi inativada! '.$e->getMessage());

            return redirect()->route('escolaridade.index');
        }

    }
}

resources/views/escolaridade/formulario.blade.php
@extends('layouts.pagina')

@section('content')

<div class="col-12">

@include('messages.alert')

@if($escolaridade->exists)
    <div class="col-12 text-center">
        <h3>EDITAR ESCOLARIDADE</h3>
    </div>

    <form action="{{route('escolaridade.update', $escolaridade)}}" method="post">
        <input type="hidden" name="_method" value="put">

@else

    <div class="col-12 text-center">
        <h3>CADASTRO DE ESCOLARIDADE</h3>
    </div>

    <form action="{{route('escolaridade.store')}}" method="post">
@endif
        {{ csrf_field() }}

            <div class="form-group col-12">
                <label>Descrição *</label>
                <input name="descricao" id="descricao" value="{{old('descricao',$escolaridade->descricao)}}" type="text" class="form-control" placeholder="Digite o nome da escolaridade" required />
            </div>


        <div class="row">
            <div class="form-group form-footer col-12 text-center" style="margin-bottom: 50px">

                <button class="btn btn-primary" type="submit">Salvar</button>

                <a class="btn btn-default" href="{{route('escolaridade.index')}}">
                    Cancelar
                </a>
            </div>
        </div>

        </form>

</div>
@endsection

resources/views/escolaridade/index.blade.php
@extends('layouts.pagina')

@section('content')

<div class="col-12">

@include('messages.alert')

        <div class="text-center col-12">
                <a href="{{route('escolaridade.create')}}" class="btn btn-large btn-primary m-3">
                    <b>Nova Escolaridade</b>
                </a>
            </div>

            <table class="table table-striped table-bordered" id="tbEscolaridade">
                <thead>
                <tr class="bg-dark text-white text-center">
                    <th>Id</th>
                    <th>Descricao</th>
                    <th>Status</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                @foreach($escolaridades as $e)
                <tr>
                    <td>{{$e->id}}</td>
                    <td>{{$e->descricao}}</td>
                    <td>{{$e->deleted_at == NULL ? 'Ativo':'Inativo' }}</td>
                    <td>

                        <div class="dropdown open">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown">
                                        Selecione
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="triggerId">

                                    @if(!$e->deleted_at)
                                        <a class="dropdown-item" href="{{action('EscolaridadeController@edit', $e)}}">Editar</a>
                                        <a class="dropdown-item"
                                        onclick="return confirm('Confirmar inativar')"
                                        href="{{url('escolaridade/remove/'.$e->id)}}">Inativar</a>

                                        @else

                                            <a class="dropdown-item" href="{{action('EscolaridadeController@ativar', $e->id)}}">Ativar</a>

                                        @endif

                                    </div>
                                </div>
                    </td>
                </tr>
                @endforeach

                </tbody>
            </table>

</div>

    <script>
        $(document).ready(function () {
            $('#tbEscolaridade').DataTable({
                "searching": true,
                "aaSorting": [[1, "asc"]],
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                },
                "columnDefs": [{
                    "targets": [-1],
                    "orderable": false
                },
                {
                "targets": [0],
                "visible": false
                }
            ],
            });
        });
    </script>
@endsection