routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Funcionario;
// use Illuminate\Routing\Route;

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::redirect('/', '/home');
    // Route::any('/home', 'HomeController@index')->name('home');
    Route::any('/home', 'HomeController@index')->name('homesuperior');

    // Funcionários
    Route::resource('/funcionario', 'FuncionarioController');

    Route::get('/funcionario/novo', function () {
        return view('funcionario.formulario');
    });
    // Cargos
    Route::resource('/cargo', 'CargoController');

    // Vínculos
    Route::resource('/vinculo', 'VinculoController');

    // Escolaridade
    Route::resource('/escolaridade', 'EscolaridadeController');
    Route::get('/escolaridade/remove/{id}', 'EscolaridadeController@delete');
    Route::get('/escolaridade/ativar/{id}', 'EscolaridadeController@ativar');

    // Grau de Parentesco
    Route::resource('/grauparentesco', 'GrauParentescoController');
    Route::get('/grauparentesco/remove/{id}', 'GrauParentescoController@delete');

    // Banco
    Route::resource('/banco', 'BancoController');
    Route::get('/banco/remove/{id}', 'BancoController@delete');

    // Tipo de Pagamento
    Route::resource('/tipopagamento', 'TipoPagamentoController');
    Route::get('/tipopagamento/remove/{id}', 'TipoPagamentoController@delete');

    // Horario de Trabalho
    Route::resource('/horariotrabalho', 'HorarioTrabalhoController');

    // Lotação
    Route::resource('/lotacao', 'LotacaoController');
    Route::get('/lotacao/remove/{id}', 'LotacaoController@delete');
    Route::get('/lotacao/ativar/{id}', 'LotacaoController@ativar');

    // Férias
    //Route::resource('/ferias','FeriasController');
    //Route::get('/ferias/cadastro/{idFunc}', 'FeriasController@createFerias');
    //Route::post('/ferias/', 'FeriasController@store');
    //Route::get('/ferias/', 'FeriasController@index');
    // Route::get('/ferias/edit/{id}', 'FeriasController@edit');
    //Route::get('resultFuncionario', array('as'=>'resultFuncionario','uses'=>'FeriasController@resultFuncionario'));

    // Férias Solicitação
    Route::resource('/ferias/solicitacao', 'FeriasSolicitacaoController');
    Route::post('/ferias/solicitacao/enviarAprovacao', 'FeriasSolicitacaoController@enviarAprovacaoSuperior');

    //Alterar Data
    Route::get('/ferias/solicitacao/{feriasSolicitacao}/edit', 'FeriasSolicitacaoController@edit')->name('edit');

    //visualizar histórico de férias
    Route::get('visualiza/historico/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoes')->name('historico');
    //visao superior ou rh
    Route::get('visualiza/avaliacao/{tipoAvaliador}/{feriasSolicitacao}', 'FeriasSolicitacaoController@visualizaAprovacoesAvaliador')->name('historicoavaliador');

    // Férias Avaliação Chefe imediato
    Route::resource('/ferias/avaliacao/superior', 'FeriasAvaliacaoSuperiorController');
    Route::get('/ferias/avaliacao/lista', 'FeriasAvaliacaoSuperiorController@index_avaliados');


    //Férias Avaliação RH
    Route::resource('/ferias/avaliacao/rh', 'FeriasAvaliacaoRHController');
    Route::get('resultAvalRHFerias', array('as' => 'resultAvalRHFerias', 'uses' => 'FeriasAvaliacaoRHController@resultAvalRHFerias'));

    // Lotação
    Route::resource('/turno', 'TurnoController');
    Route::get('/turno/remove/{id}', 'TurnoController@delete');
    Route::get('/turno/ativar/{id}', 'TurnoController@ativar');
});

app/TipoPagamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class TipoPagamento extends Model
{
    protected $table = "tipo_pagamento";
    public $fillable = ['codigo', 'descricao', 'usuario_id_fk'];

    //verifica se já existe codigo cadastrado
   public function existeCodigocadastrado($codigo, $id){

    if($id){//update

        $existe = DB::table('tipo_pagamento')->where([
            ['codigo', '=', $codigo],
            ['id', '<>', $id],
        ])->count();

    }else{//store
        $existe = DB::table('tipo_pagamento')->where([
            ['codigo', '=', $codigo],
        ])->count();
    }

    if($existe > 0){
        return true;
    }else{
        return false;
    }

}
}

app/Http/Controllers/TipoPagamentoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTipoPagamento;
use App\TipoPagamento;
use Illuminate\Http\Request;
use Request as rq;

class TipoPagamentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tipopagamento = TipoPagamento::orderBy('descricao')->get();

        return view('tipopagamento.index', compact('tipopagamento'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tipopagamento = new TipoPagamento();

        return view('tipopagamento.formulario', compact('tipopagamento'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTipoPagamento $request)
    {
        $tipopagamento = new TipoPagamento();
        $existeCodigo = $tipopagamento->existeCodigocadastrado($request->codigo, NULL);

        if($existeCodigo){
            rq::session()->flash('status-not', 'Já existe um tipo de pagamento cadastrado com o código informado.');
            return redirect()->back()->withInput();
        }

        try{

            $tipopagamento = TipoPagamento::create([
                'codigo' => $request->codigo,
                'descricao' => $request->descricao,
                'usuario_id_fk' => auth()->user()->id
            ]);

            if($tipopagamento){
                rq::session()->flash('status', 'Tipo de pagamento cadastrado com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de pagamento.');
            }

        }catch(\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de pagamento. '.$e->getMessage());
        }

        return redirect()->route('tipopagamento.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TipoPagamento  $tipoPagamento
     * @return \Illuminate\Http\Response
     */
    public function show(TipoPagamento $tipopagamento)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TipoPagamento  $tipoPagamento
     * @return \Illuminate\Http\Response
     */
    public function edit(TipoPagamento $tipopagamento)
    {
        return view('tipopagamento.formulario', compact('tipopagamento'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TipoPagamento  $tipoPagamento
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTipoPagamento $request, TipoPagamento $tipopagamento)
    {

        $existeCodigo = $tipopagamento->existeCodigocadastrado($request->codigo, $tipopagamento->id);

        if($existeCodigo){
            rq::session()->flash('status-not', 'Já existe um tipo de pagamento cadastrado com o código informado.');
            return redirect()->back()->withInput();
        }

        try{

            $tipopagamento = $tipopagamento->update([
                'codigo' => $request->codigo,
                'descricao' => $request->descricao,
            ]);

            if($tipopagamento){
                rq::session()->flash('status', 'Tipo de pagamento atualizado com sucesso.');
            }else{
                rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de pagamento.');
            }

        }catch(\Exception $e){
            rq::session()->flash('status-not', 'Ocorreu um erro ao salvar tipo de pagamento. '.$e->getMessage());
        }

        return redirect()->route('tipopagamento.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TipoPagamento  $tipoPagamento
     * @return \Illuminate\Http\Response
     */
    public function destroy(TipoPagamento $tipoPagamento)
    {
        //
    }

    public function delete($id)
    {
        $tipopagamento = TipoPagamento::findOrFail($id);

        try{
            $tipopagamento->delete();
            rq::session()->flash('status', 'Tipo de pagamento '.$tipopagamento->descricao.' excluído com sucesso.');
            return redirect()->route('tipopagamento.index');
        }
        catch (\Exception $e){

            if($e->getCode() == 23000 ){
                rq::session()->flash('status-not', 'Tipo de pagamento não foi excluído. O mesmo está sendo utilizado em outro cadastro! ');
            }else{
                rq::session()->flash('status-not', 'Tipo de pagamento não foi excluído! '.$e->getMessage());
            }

            return redirect()->route('tipopagamento.index');
        }

    }
}

resources/views/tipoPagamento/formulario.blade.php
@extends('layouts.pagina')

@section('content')

<div class="col-12">

@include('messages.alert')

@if($tipopagamento->exists)
    <div class="col-12 text-center">
        <h3>EDITAR TIPO DE PAGAMENTO</h3>
    </div>

    <form action="{{route('tipopagamento.update', $tipopagamento)}}" method="post">
        <input type="hidden" name="_method" value="put">

@else

    <div class="col-12 text-center">
        <h3>CADASTRO DE TIPO DE PAGAMENTO</h3>
    </div>

    <form action="{{route('tipopagamento.store')}}" method="post">
@endif
        {{ csrf_field() }}

            <div class="form-group col-3">
                <label>Código *</label>
                <input name="codigo" id="codigo" value="{{old('codigo',$tipopagamento->codigo)}}" type="text" class="form-control codetipopagamento"  required />
            </div>

            <div class="form-group col-9">
                <label>Descrição *</label>
                <input name="descricao" id="descricao" value="{{old('descricao',$tipopagamento->descricao)}}" type="text" class="form-control" placeholder="Digite o nome do tipo de pagamento" required />
            </div>


        <div class="row">
            <div class="form-group form-footer col-12 text-center" style="margin-bottom: 50px">

                <button class="btn btn-primary" type="submit">Salvar</button>

                <a class="btn btn-default" href="{{route('tipopagamento.index')}}">
                    Cancelar
                </a>
            </div>
        </div>

        </form>

</div>
@endsection

resources/views/tipoPagamento/index.blade.php
@extends('layouts.pagina')

@section('content')

<div class="col-12">

@include('messages.alert')

        <div class="text-center col-12">
                <a href="{{route('tipopagamento.create')}}" class="btn btn-large btn-primary m-3">
                    <b>Novo Tipo de Pagamento</b>
                </a>
            </div>

            <table class="table table-striped table-bordered" id="tbTipoPagamento">
                <thead>
                <tr class="bg-dark text-white text-center">
                    <th>Id</th>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                @foreach($tipopagamento as $t)
                <tr>
                    <td>{{$t->id}}</td>
                    <td>{{$t->codigo}}</td>
                    <td>{{$t->descricao}}</td>
                    <td>

                        <div class="dropdown open">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown">
                                        Selecione
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="triggerId">
                                        <a class="dropdown-item" href="{{action('TipoPagamentoController@edit', $t)}}">Editar</a>
                                        <a class="dropdown-item"
                                        onclick="return confirm('Confirmar exclusão')"
                                        href="{{url('tipopagamento/remove/'.$t->id)}}">Excluir</a>
                                    </div>
                                </div>
                    </td>
                </tr>
                @endforeach

                </tbody>
            </table>

</div>

    <script>
        $(document).ready(function () {
            $('#tbTipoPagamento').DataTable({
                "searching": true,
                "aaSorting": [[2, "asc"]],
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                },
                "columnDefs": [{
                    "targets": [-1],
                    "orderable": false
                },
                {
                "targets": [0],
                "visible": false
                }],

            });
        });
    </script>
@endsection